# Generated by Django 5.0.3 on 2024-03-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('signal_type', models.CharField(max_length=10)),
            ],
        ),
    ]
